name: Build and Release

on:
  push:
    tags:
      - "v*" # só roda quando criar uma tag tipo v1.0.0

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Instalar dependências (produção)
        run: npm install --production

      # =========================
      # SERVER .EXE
      # =========================
      - name: Build server.exe
        run: npm run build:server

      # =========================
      # CLIENT .EXE
      # =========================
      - name: Build client.exe
        run: npm run build:client

      # =========================
      # CLIENT
      # =========================
      - name: Zipar client
        run: |
          zip -r client.zip \
            src/client \
            node_modules \
            package.json \
            src/client/.env.example

      # =========================
      # SERVER (zip Node.js)
      # =========================
      - name: Zipar server (sem client)
        run: |
          zip -r server.zip \
            src \
            node_modules \
            package.json \
            .env.example \
            -x "src/client/*"

      # =========================
      # RELEASE
      # =========================
      - name: Criar release e anexar arquivos
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/server.exe
            dist/client.exe
            client.zip
            server.zip
