name: Release

on:
  workflow_run:
    workflows: ["Smoke Test"]
    types:
      - completed

permissions:
  contents: write
  actions: read

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Baixar artefatos aprovados
        uses: actions/download-artifact@v4
        with:
          name: tested-artifacts
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ler nome da tag
        id: version
        run: echo "tag=$(cat version.txt)" >> $GITHUB_OUTPUT

      - name: Criar release e anexar arquivos
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          files: |
            dist/server.exe
            dist/client.exe
            client.zip
            server.zip
